export enum PermissionEnum {
	FindUsers = 'find_users',
	FindUser = 'find_user',
	CreateUser = 'create_user',
	UpdateUserInformation = 'update_user_information',
	ResetUserPassword = 'reset_user_password',
	LockUser = 'lock_user',
	UnlockUser = 'unlock_user',
	FindProductsForRole = 'find_products_for_role',
	CreateProduct = 'create_product',
	CreateProductSchedule = 'create_product_schedule',
	UpdateProductInformation = 'update_product_information',
	FindProductScheduleBySupplierId = 'find_product_schedule_by_supplier_id',
	FindUsersInProductScheduleByProductScheduleId = 'find_users_in_product_schedule_by_product_schedule_id',
	UpdateCompletedProductSchedule = 'update_completed_product_schedule',
	DeleteProductScheduleByProductScheduleId = 'delete_product_schedule_by_product_schedule_id',
	CreateDiscount = 'create_discount',
	DeleteDiscountByDiscountId = 'delete_discount_by_discount_id',
	FindDiscountsByUserId = 'find_discounts_by_user_id',
	AssignProductSchedulesToDiscount = 'assign_product_schedules_to_discount',
	UpdatePaidBill = 'update_paid_bill',
	DeleteProductRateByProductRateId = 'delete_product_rate_by_product_rate_id',
}
