export const optionSortAttraction = [
	{ id: '1', label: 'Name', value: 'name' },
	{ id: '2', label: 'Time', value: 'time' },
	{ id: '3', label: 'Quantity available', value: 'quantityAvailable' },
	{ id: '4', label: 'Age', value: 'age' },
	{ id: '5', label: 'Quantity completed', value: 'quantityCompleted' },
	{ id: '6', label: 'Quantity rate', value: 'quantityRate' },
	{ id: '7', label: 'Average rate', value: 'avgRate' },
	{ id: '8', label: 'Location name', value: 'locationName' },
	{ id: '9', label: 'City', value: 'city' },
	{ id: '10', label: 'Created at', value: 'createAt' },
	{ id: '11', label: 'Updated at', value: 'updateAt' },
	{ id: '12', label: 'Deleted at', value: 'deletedAt' },
	{ id: '13', label: 'Status', value: 'status' },
];
