import { EUserRole, EUserStatus, TUser } from '@/types';

export const mockUsers: TUser[] = [
	{
		id: 'clv0lqj0g0000o7l6gswv42kk',
		name: 'Alice Nguyen',
		roleName: EUserRole.tourist,
		image: 'https://example.com/avatar1.png',
		gender: 'female',
		email: 'alice@gmail.com',
		dateOfBirth: new Date('1995-06-15'),
		phoneNumber: '0905123456',
		address: '123 Tran Phu, Da Nang',
		balance: 100,
		point: 50,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.active,
	},
	{
		id: 'clv0lqj0g0001o7l6gswv42kl',
		name: 'Bob Tran',
		roleName: EUserRole.supplier,
		image: 'https://example.com/avatar2.png',
		gender: 'male',
		email: 'bob@supplier.vn',
		dateOfBirth: new Date('1988-02-10'),
		phoneNumber: '0912345678',
		address: '45 Nguyen Hue, Hue',
		balance: 500,
		point: 200,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.active,
	},
	{
		id: 'clv0lqj0g0002o7l6gswv42km',
		name: 'Charlie Le',
		roleName: EUserRole.admin,
		image: 'https://example.com/avatar3.png',
		gender: 'male',
		email: 'charlie@admin.com',
		dateOfBirth: new Date('1990-09-01'),
		phoneNumber: '0933344555',
		address: '456 Le Duan, HCMC',
		balance: 0,
		point: 1000,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.active,
	},
	{
		id: 'clv0lqj0g0003o7l6gswv42kn',
		name: 'Diana Pham',
		roleName: EUserRole.tourist,
		image: 'https://example.com/avatar4.png',
		gender: 'female',
		email: 'diana@yahoo.com',
		dateOfBirth: new Date('1999-12-25'),
		phoneNumber: '0988888888',
		address: '789 Bach Dang, Da Nang',
		balance: 20,
		point: 10,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.locked,
	},
	{
		id: 'clv0lqj0g0004o7l6gswv42ko',
		name: 'Ethan Vo',
		roleName: EUserRole.supplier,
		image: 'https://example.com/avatar5.png',
		gender: 'male',
		email: 'ethan@supply.com',
		dateOfBirth: null,
		phoneNumber: null,
		address: null,
		balance: 1000,
		point: 150,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.active,
	},
	{
		id: 'clv0lqj0g0005o7l6gswv42kp',
		name: 'Fiona Dang',
		roleName: EUserRole.tourist,
		image: 'https://example.com/avatar6.png',
		gender: 'female',
		email: 'fiona@gmail.com',
		dateOfBirth: new Date('2001-04-22'),
		phoneNumber: '0922233344',
		address: '123 Hoang Dieu, Da Nang',
		balance: 300,
		point: 120,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.inactive,
	},
	{
		id: 'clv0lqj0g0006o7l6gswv42kq',
		name: 'George Bui',
		roleName: EUserRole.admin,
		image: 'https://example.com/avatar7.png',
		gender: 'male',
		email: 'george@admin.com',
		dateOfBirth: new Date('1985-08-18'),
		phoneNumber: '0966677788',
		address: 'Ha Noi, Vietnam',
		balance: 0,
		point: 999,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.active,
	},
	{
		id: 'clv0lqj0g0007o7l6gswv42kr',
		name: 'Hannah Vu',
		roleName: EUserRole.tourist,
		image: 'https://example.com/avatar8.png',
		gender: 'female',
		email: 'hannah.tourist@mail.com',
		dateOfBirth: new Date('1998-03-03'),
		phoneNumber: null,
		address: null,
		balance: 70,
		point: 30,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.locked,
	},
	{
		id: 'clv0lqj0g0008o7l6gswv42ks',
		name: 'Ivan Hoang',
		roleName: EUserRole.supplier,
		image: 'https://example.com/avatar9.png',
		gender: 'male',
		email: 'ivan@supply.vn',
		dateOfBirth: new Date('1993-05-10'),
		phoneNumber: '0977766655',
		address: 'Vung Tau, Vietnam',
		balance: 250,
		point: 60,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.inactive,
	},
	{
		id: 'clv0lqj0g0009o7l6gswv42kt',
		name: 'Jenny Ly',
		roleName: EUserRole.tourist,
		image: 'https://example.com/avatar10.png',
		gender: 'female',
		email: 'jenny.ly@gmail.com',
		dateOfBirth: new Date('2000-10-20'),
		phoneNumber: '0911222333',
		address: 'Can Tho, Vietnam',
		balance: 80,
		point: 45,
		createAt: new Date(),
		updateAt: new Date(),
		deletedAt: null,
		status: EUserStatus.active,
	},
];
