import { PermissionEnum } from '../permission.enum';

export enum PermissionForAdminEnum {
	FindUsers = PermissionEnum.FindUsers,
	FindUser = PermissionEnum.FindUser,
	CreateUser = PermissionEnum.CreateUser,
	UpdateUserInformation = PermissionEnum.UpdateUserInformation,
	ResetUserPassword = PermissionEnum.ResetUserPassword,
	LockUser = PermissionEnum.LockUser,
	UnlockUser = PermissionEnum.UnlockUser,
	FindProductsForRole = PermissionEnum.FindProductsForRole,
	CreateProduct = PermissionEnum.CreateProduct,
	CreateProductSchedule = PermissionEnum.CreateProductSchedule,
	UpdateProductInformation = PermissionEnum.UpdateProductInformation,
	FindProductScheduleBySupplierId = PermissionEnum.FindProductScheduleBySupplierId,
	FindUsersInProductScheduleByProductScheduleId = PermissionEnum.FindUsersInProductScheduleByProductScheduleId,
	UpdateCompletedProductSchedule = PermissionEnum.UpdateCompletedProductSchedule,
	DeleteProductScheduleByProductScheduleId = PermissionEnum.DeleteProductScheduleByProductScheduleId,
	CreateDiscount = PermissionEnum.CreateDiscount,
	DeleteDiscountByDiscountId = PermissionEnum.DeleteDiscountByDiscountId,
	FindDiscountsByUserId = PermissionEnum.FindDiscountsByUserId,
	AssignProductSchedulesToDiscount = PermissionEnum.AssignProductSchedulesToDiscount,
	UpdatePaidBill = PermissionEnum.UpdatePaidBill,
	DeleteProductRateByProductRateId = PermissionEnum.DeleteProductRateByProductRateId,
}
